
main:
	/Applications/MATLAB_R2011a.app/bin/mex -I/usr/local/include/eigen3/ chromfwdbackCPP.cpp chromhmm.cpp
	/Applications/MATLAB_R2011a.app/bin/mex -I/usr/local/include/eigen3/ chromlogprobCPP.cpp chromhmm.cpp
#	/Applications/MATLAB_R2011a.app/bin/mex -I/usr/local/include/eigen3/ FilterFwdC.cpp
#	/Applications/MATLAB_R2011a.app/bin/mex -I/usr/local/include/eigen3/ SmoothBackC.cpp
